aliyun-UED/aliyun-sdk-js

- .gitignore
- apis/batchcompute-2015-06-30.json
- lib/services.js
- lib/services/batchcompute.js
- lib/signers/batchcompute.js
- lib/signers/request_signer.js
- samples/batchcompute/CreateJob.js
- samples/batchcompute/GetJob.js
- samples/batchcompute/GetJobStatus.js
- samples/batchcompute/ListImages.js
- samples/batchcompute/ListJobStatus.js
- samples/batchcompute/ListTaskStatus.js
- samples/batchcompute/StartJob.js
- samples/batchcompute/StopJob.js
- samples/batchcompute/UpdateJobPriority.js
- samples/batchcompute/batchcompute.js
- test/README.md
- test/batchcompute/config.js
- test/batchcompute/index.js
- test/index.js
1. batchcompute sdk提交
2. 我觉得test目录是很有必要的，.gitignore中的test*太霸道了，先去掉
> batchcompute first commit, 去掉.gitignore中的test*

- apis/batchcompute-2015-06-30.json
- lib/services/batchcompute.js
- samples/batchcompute/CreateJob.js
- samples/batchcompute/GetJobDescription.js
- samples/batchcompute/ListJobs.js
- samples/batchcompute/ListTasks.js
- test/batchcompute/index.js
> 修改方法名，与API一致

- lib/services/batchcompute.js
- samples/batchcompute/DeleteJob.js
1. 后端api修改了，增加了Code字段，sdk 需要做相应修改。
2. 增加DeleteJob sample
> API error code相应修改

- apis/batchcompute-2015-11-11.json
- samples/batchcompute/2015-11-11/ChangeClusterDesiredVMCount.js
- test/batchcompute/2015-11-11.js
1. 增加 changeClusterDesiredVMCount 接口
2. 创建Cluster接口中 增加 UserData 字段
> Batchcompute20150112

- apis/sls-2015-06-01.json
- lib/services/sls.js
- lib/signers/sls.js
- samples/sls/BatchGetLogs.js
- samples/sls/CreateLogStore.js
- samples/sls/DeleteLogStore.js
- samples/sls/GetHistograms.js
- samples/sls/GetLogStore.js
- samples/sls/GetLogs.js
- samples/sls/Index.js
- samples/sls/PutLogs.js
- samples/sls/Shard.js
- samples/sls/sls.js
> commit sls sdk 0.6.0

- lib/services/sls.js
> fix bug of serialize protobuf error

- apis/push-2015-08-27.json
> push sdk update

- apis/push-2016-08-01.json
> pop nosejs sdk add 2016-08-01

- apis/green-2016-11-24.json
- samples/green/AsyncImageDetectionResultSample.js
- samples/green/AsyncImageDetectionSample.js
- samples/green/SyncImageDetectionSample.js
- samples/green/TexrtAntispamDetectionSample.js
- samples/green/TextKeywordFilterSample.js
- samples/green/TextWordCorrectSample.js
> green-sdk_v20161124

- samples/jaq/AfsCheck.js
> fix AfsCheck.js

- apis/green-2016-12-16.json
> green-2016-12-16-bugfix

- samples/sls/Readme.md
> 更新 sls sdk 目前支持最新的 api 版本

- browser.js
- samples/ess/test.js
> Add api: ess-v20140828

- apis/oss-2013-10-15.json
- samples/oss/PutBucket.js
> 创建bucket支持Archive类型

- apis/dns-2015-01-09.json
- samples/dns/test.js
支持如下操作：
- 获取域名列表
- 获取域名信息
- 获取解析记录列表
- 添加解析记录
- 获取解析记录信息
- 删除解析记录
> 支持 dns API

- apis/oss-2013-10-15.json
根据[GetObjectMeta](https://help.aliyun.com/document_detail/31985.html) ，增加取文件meta信息的方法
> OSS增加取object meta信息

- apis/opensearch-2015-01-01.json
> Update opensearch-2015-01-01.json for scroll search

- apis/sls-2015-06-01.json
> Add new alert api

- lib/config.js
- lib/event_listeners.js
- lib/services/oss.js
- lib/signers/oss.js
- samples/oss/GetObjectWithCname.js
- samples/oss/GetObjectWithRequestPayer.js
support canme and requestpayer for oss
> feat: support canme and requestpayer for oss

- package.json
> chore: upgrade version
